#!/usr/bin/env bash
# installing nginx on my remote server

apt-get update -y
apt-get upgrade -y
mkdir /etc/nginx/html -p
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
    listen  80 default_server;
    listen  [::]:80 default_server;
    root    /etc/nginx/html;
    index   index.html;
}" > /etc/nginx/sites-available/default
service nginx restart
