#!/usr/bin/env bash
# installing nginx on my remote server

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    server_name localhost;
    location / {
        root /etc/nginx/html;
        index index.html;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
