#!/usr/bin/env bash
# This bash script is displaying Best School 10 times

var_a='Best School'
for var_a in 'Best School'
do
    echo $var_a
    echo $var_a
    echo $var_a
    echo $var_a
    echo $var_a
    echo $var_a
    echo $var_a
    echo $var_a
    echo $var_a
    echo $var_a
done
