#!/bin/env bash
# This bash script will display Best School 10 times

for var_a in Best_School
do
    echo $var_a
    echo $var_a
    echo $var_a
    echo $var_a
    echo $var_a
    echo $var_a
    echo $var_a
    echo $var_a
    echo $var_a
    echo $var_a
done
