#!/usr/bin/env bash
# This bash script will display Best School 10 times, but the 9th iteration, it also displays Hi on a seperate line'

i=1

while [ $i -le 10 ]
do
      echo 'Best School'
      if [  $i -eq 9  ];
      then
	  echo 'Hi'
      fi
      ((i++))
done
