#!/usr/bin/env bash
# This bash script will display the numbers 1-20, after 4 it shows bad luck from China, after 9 it shows bad luck from Japan, after 17 it shows bad luck from Italy.

i=1
while [ $i -le 20 ]
do
    echo $i
    case $i in
	4)
	    echo 'bad luck from China'
	    ;;
	9)
	    echo 'bad luck from Japan'
	    ;;
	17)
	    echo 'bad luck from Italy'
	    ;;
    esac
    i=$((i + 1))
done
