#!/usr/bin/env bash
# This bash script will display the time for 12 hours and 59 minutes

i=0
h=0
m=0
while [ $i -le 779 ]
do
    if (( i % 60 == 0 ))
    then
	echo "Hour: $h"
    m=0
    ((h++))
    else 
	echo "$m"
    fi
    ((i++))
    ((m++))

done
