#!/usr/bin/env bash
# This bash script will give you information about the school file

i="school"
if [ -e "$i" ]
then
    echo "school file exists"
    if [ ! -s "$i" ]
    then
	echo "school file is not empty"
    else
	echo "school files is empty"
    fi
    if [ -f "$i" ]
    then
	echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
