#!/usr/bin/env bash
# write a bash script that uses ```ssh``` to connect
# to your server using the private key ```~/.ssh/school```
# with the user ```ubuntu```

ssh -i ~/.ssh/school ubuntu@15.236.208.107
