#!/usr/bin/env bash
# installing nginx on the second remote server

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html /etc/nginx/html/404.html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
printf %s "server {
    listen  80 default_server;
    listen  [::]:80 default_server;
    root    /etc/nginx/html;
    index   index.html;
    add_header X-Served-By $HOSTNAME;
    location /redirect_me {
        return 301 http://tatertotsaremylife.tech/;
    }
    error_page 404 /404.html;
    location /404 {
    root /etc/nginx/html;
    internal;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
