#!/usr/bin/env bash
# iNsTaLl ThE lOaD bAlAnCeR

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
cat <<EOT > /etc/haproxy/haproxy.cfg
defaults
    mode    http
frontend http-in
    bind    *:80
    default_backend servers
backend servers
    balance roundrobin
    server  5580-web-01 52.47.77.6:80 check
    server  5580-web-02 15.237.132.139:80 check
EOT
sudo service haproxy restart
