#!/usr/bin/env bash
# setup ufw to allow ports
# 22 == ssh
# 80 == HTTP
# 443 == HTTPS SSL
# 3306 == MySQL

sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw allow 3306/tcp
sudo ufw enable
